version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: monthly }
    groups:
      frontend: { patterns: ['*'] }
  - package-ecosystem: npm
    directory: /worker
    schedule: { interval: monthly }
    groups:
      worker: { patterns: ['*'] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
