export const knowledge = [
  { id:'overview', title:'Executive overview', url:'/CV-Joseph-Hanna/', text:'Joseph Hanna is an executive technology leader targeting VP of IT, Head of IT, Director of IT, and CIO-track roles. He is based in Orange County, California and open to remote and Southern California hybrid roles. He has more than 20 years of experience in technology strategy, cybersecurity, enterprise applications, cloud modernization, and IT operations.' },
  { id:'repipe', title:'Repipe Specialists experience', url:'/CV-Joseph-Hanna/experience', text:'At Repipe Specialists Joseph served as Senior Director then Vice President of Information Technology from June 2022 to September 2024. He was the sole internal IT leader and later selected and governed an MSP for help desk and incident management. Company headcount grew from 50+ to 100+. Approved outcomes: 30% less downtime, 40% lower vulnerability exposure, 35% faster incident resolution, 25% faster executive decisions, 20% workflow efficiency improvement, and technology support for 30% year-over-year business growth.' },
  { id:'netsuite', title:'NetSuite case study', url:'/CV-Joseph-Hanna/case-studies/repipe-netsuite', text:'At Repipe Specialists Joseph led the NetSuite implementation, served as business owner and executive sponsor, personally led third-party integrations, and administered the environment. Partners contributed selected technical implementation work.' },
  { id:'safeway', title:'SafewayTax Microsoft 365 case study', url:'/CV-Joseph-Hanna/case-studies/safeway-microsoft-365', text:'At SafewayTax Joseph was IT Consultant from May 2025 through August 2026 for a 75+ user organization. He migrated 85 people from Google Workspace to Microsoft 365. Approved outcomes: 99.9% infrastructure uptime, 40% lower security risk, 30% operational efficiency improvement, 20% productivity improvement, 25% less downtime, 50% faster onboarding, and 45% fewer repeat tickets.' },
  { id:'jaidah', title:'Jaidah enterprise platforms case study', url:'/CV-Joseph-Hanna/case-studies/jaidah-enterprise-platforms', text:'At Jaidah Group from March 2006 to October 2017 Joseph led the IT department through direct and indirect lines, growing it from 9 to 17. The group had 1,250 employees across 17 subsidiaries. He led an approximately $2M SAP S/4HANA program across 15 non-automotive subsidiaries and 650 employees, plus one Incadea implementation for each of two automotive subsidiaries covering about 600 employees. The programs materially improved processing and reporting and standardized automotive operations.' },
  { id:'datacenter', title:'Jaidah data center case study', url:'/CV-Joseph-Hanna/case-studies/jaidah-data-center', text:'Joseph led a successful multi-tenant data-center build and migration at Jaidah Group, achieving 99.99% service availability. Detailed architecture is intentionally not public.' },
  { id:'operations', title:'Global end-user operations case study', url:'/CV-Joseph-Hanna/case-studies/global-end-user-operations', text:'At AVEVA Joseph coordinated ten people without formal management authority for a global end-user computing function supporting approximately 2,800 employees and endpoints. At Cherokee Federal, he led seven direct reports across three shifts supporting 2,400 employees and computers, approximately 1,000 mobile devices, and 650 additional tablets in a 24/7 model.' },
  { id:'credentials', title:'Credentials', url:'/CV-Joseph-Hanna/credentials', text:'Education: MBA in Project Management from International Business School of Scandinavia; MBA in Business Management from Rome Business School; Bachelor of Applied Science in Information Technology from American Business and Technology University; Bachelor of Commerce in Accounting from Ain Shams University. Credentials include PMP, ITIL Foundation, MCTS, MCP, DCDA, CIW 410, CIW 430, Scrum Fundamentals, AI Fluency Framework and Foundations, AI Fluency for Small Businesses, and Claude 101.' },
]
